### ISSUE TITLE
Next version

### ISSUE THREAD

**Issue by terax6669** [jquagliatini/pinia-class#2]
Since vue-class-component is deprecated, will you consider adding support for vue-facing-decorator?

**Comment by jquagliatini** [comment]
Hello @terax6669, I was just informed that vue-class-component was deprecated a few days ago. I might look into it in the following days.

**Comment by jquagliatini** [comment]
@terax6669 I just published [v0.0.5](https://www.npmjs.com/package/pinia-class/v/0.0.5) which introduces vue-facing-decorator. Hope that helps
